type Lang="en"|"ru";
const copy={
 en:{nav:["Platform","Missions","Contact"],console:"OPEN CONSOLE ↗",status:"SYSTEMS NOMINAL",eyebrow:"SPACE DOMAIN INTELLIGENCE",title:<>See what’s<br/><span>beyond.</span></>,lead:"Real-time orbital awareness for teams operating at the edge of possibility.",explore:"EXPLORE THE PLATFORM",metrics:[["14,204","Objects tracked"],["99.98%","Signal uptime"],["07","Active missions"]],live:<>Live network<br/>status</>,cap:"[ 01 ] CAPABILITIES",platformTitle:<>A clearer picture<br/>of a crowded sky.</>,map:"LIVE ORBITAL MAP / 2026.204",panels:[["Persistent tracking","Continuous observation across LEO, MEO and GEO with sub-second updates."],["Collision intelligence","Autonomous conjunction screening with decision-ready risk models."],["Mission planning","Simulate maneuvers and understand the operational picture before launch."]],mission:"MISSION / ODYSSEY-4",missionTitle:<>12 days.<br/>One new orbit.</>,missionLead:"Supporting the next generation of climate observation.",log:"VIEW MISSION LOG ↗",footer:"Earth · Moon · Beyond"},
 ru:{nav:["Платформа","Миссии","Контакты"],console:"ОТКРЫТЬ КОНСОЛЬ ↗",status:"СИСТЕМЫ В НОРМЕ",eyebrow:"РАЗВЕДКА КОСМИЧЕСКОЙ ОБСТАНОВКИ",title:<>Видеть то,<br/><span>что дальше.</span></>,lead:"Орбитальная обстановка в реальном времени для команд, работающих на границе возможного.",explore:"ИЗУЧИТЬ ПЛАТФОРМУ",metrics:[["14 204","объекта отслеживается"],["99,98%","доступность сигнала"],["07","активных миссий"]],live:<>Сеть работает<br/>в реальном времени</>,cap:"[ 01 ] ВОЗМОЖНОСТИ",platformTitle:<>Ясная картина<br/>перегруженного неба.</>,map:"ОРБИТАЛЬНАЯ КАРТА / 2026.204",panels:[["Непрерывное слежение","Постоянное наблюдение на низких, средних и геостационарных орбитах с обновлением за доли секунды."],["Аналитика сближений","Автономная проверка опасных сближений и готовые к решению модели рисков."],["Планирование миссий","Моделируйте манёвры и оценивайте обстановку до запуска."]],mission:"МИССИЯ / ODYSSEY-4",missionTitle:<>12 дней.<br/>Одна новая орбита.</>,missionLead:"Поддерживаем новое поколение климатических наблюдений.",log:"ОТКРЫТЬ ЖУРНАЛ МИССИИ ↗",footer:"Земля · Луна · Дальше"}
} as const;
export function SiteHome({lang}:{lang:Lang}){const c=copy[lang],prefix=lang==="ru"?"/ru":"/en";return <main data-lang={lang}><div className="lang-float"><a className={lang==="en"?"active":""} href="/">EN</a><a className={lang==="ru"?"active":""} href="/ru">RU</a></div><nav><a className="mark" href="#top"><span>O</span>ORBITAL/LAB</a><div><a href={`${prefix}/platform`}>{c.nav[0]}</a><a href={`${prefix}/missions`}>{c.nav[1]}</a><a href="#contact">{c.nav[2]}</a></div><a className="console" href="#platform">{c.console}</a></nav>
 <section className="hero" id="top"><div className="grid" aria-hidden="true"/><div className="status"><i/> {c.status} <span>UTC 21:47:03</span></div><div className="copy"><p>{c.eyebrow}</p><h1>{c.title}</h1><p className="lead">{c.lead}</p><a href="#platform">{c.explore} <b>↘</b></a></div><div className="orbit" aria-hidden="true"><div className="planet"/><i/><i/><i/><span>LEO-2407</span></div><div className="coords">LAT 28.3922° N<br/>LNG 80.6077° W<br/>ALT 408.2 KM</div></section>
 <section className="metrics">{c.metrics.map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}<p>{c.live} <i/></p></section><section className="platform" id="platform"><div className="label">{c.cap}</div><h2>{c.platformTitle}</h2><div className="dashboard"><div className="radar"><div className="rings"/><span className="sat s1">◆</span><span className="sat s2">◆</span><span className="sat s3">◆</span><small>{c.map}</small></div><div className="panels">{c.panels.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="mission" id="missions"><span>{c.mission}</span><h2>{c.missionTitle}</h2><p>{c.missionLead}</p><a href="#contact">{c.log}</a></section><footer id="contact"><a className="mark" href="#top"><span>O</span>ORBITAL/LAB</a><p>{c.footer}</p><p>© 2026 OL SYSTEMS</p></footer></main>}
