type Lang="en"|"ru";
const content={
 en:{brand:"ORBITAL/LAB",back:"Back to base",switchTo:"/ru",switchLabel:"RU",title:"Intelligence for every orbit.",lead:"Know what is moving, what is changing and what needs your attention.",pages:{
  platform:{label:"Platform",eyebrow:"SPACE DOMAIN INTELLIGENCE",title:"One operating picture.",intro:"A unified environment for tracking, risk analysis and mission planning across every orbital regime.",cards:[["Persistent tracking","14,000+ objects updated in near real time."],["Risk engine","Autonomous conjunction screening with explainable alerts."],["Mission studio","Model maneuvers before committing fuel and time."]],note:"99.98% network uptime across seven sensor regions."},
  missions:{label:"Missions",eyebrow:"ACTIVE OPERATIONS / 07",title:"Built for decisive moments.",intro:"From climate constellations to lunar logistics, teams use Orbital Lab to move with clarity.",cards:[["Odyssey-4","Climate observation · LEO · active"],["Lumen Relay","Communications · MEO · commissioning"],["Artemis Cargo","Lunar logistics · cislunar · planned"]],note:"Operational support is available around the clock."}
 }},
 ru:{brand:"ORBITAL/LAB",back:"На базу",switchTo:"/",switchLabel:"EN",title:"Аналитика для каждой орбиты.",lead:"Знайте, что движется, что меняется и где требуется решение.",pages:{
  platform:{label:"Платформа",eyebrow:"РАЗВЕДКА КОСМИЧЕСКОЙ ОБСТАНОВКИ",title:"Единая картина неба.",intro:"Общая среда для слежения, анализа рисков и планирования миссий на всех орбитах.",cards:[["Постоянное слежение","Более 14 000 объектов почти в реальном времени."],["Модель рисков","Автономный анализ сближений с понятными сигналами."],["Студия миссий","Проверка манёвров до расхода топлива и времени."]],note:"Доступность сети 99,98% в семи сенсорных регионах."},
  missions:{label:"Миссии",eyebrow:"АКТИВНЫЕ ОПЕРАЦИИ / 07",title:"Для решающих моментов.",intro:"От климатических группировок до лунной логистики — команды действуют с ясной картиной.",cards:[["Odyssey-4","Наблюдение климата · НОО · активно"],["Lumen Relay","Связь · СОО · ввод в строй"],["Artemis Cargo","Лунная логистика · планируется"]],note:"Операционная поддержка работает круглосуточно."}
 }}} as const;
export function LocalizedLanding({lang}:{lang:Lang}){const c=content[lang];return <main className="locale-home"><header><a href="/">{c.brand}</a><a href={c.switchTo}>{c.switchLabel}</a></header><section><p>{lang==="ru"?"СИСТЕМЫ В НОРМЕ":"SYSTEMS NOMINAL"}</p><h1>{c.title}</h1><span>{c.lead}</span><div>{Object.entries(c.pages).map(([s,p])=><a key={s} href={`/${lang}/${s}`}>{p.label} ↘</a>)}</div></section></main>}
export function DetailPage({lang,slug}:{lang:Lang;slug:string}){const c=content[lang];const p=c.pages[slug as keyof typeof c.pages]||c.pages.platform;return <main className="inner-page"><header><a href="/">{c.brand}</a><nav>{Object.entries(c.pages).map(([s,v])=><a key={s} href={`/${lang}/${s}`}>{v.label}</a>)}<a href={c.switchTo}>{c.switchLabel}</a></nav></header><section className="inner-hero"><p>{p.eyebrow}</p><h1>{p.title}</h1><span>{p.intro}</span></section><section className="inner-cards">{p.cards.map(([t,d],i)=><article key={t}><small>[0{i+1}]</small><h2>{t}</h2><p>{d}</p><a href="mailto:ops@orbital.example">{lang==="ru"?"ОТКРЫТЬ ДАННЫЕ":"OPEN DATA"} ↗</a></article>)}</section><footer><p>{p.note}</p><a href="/">{c.back} ↑</a></footer></main>}
